service: utas-etl
plugins:
  - serverless-python-requirements

useDotEnv: true

provider:
  name: aws
  runtime: python3.8
  region: eu-west-1
  iam:
    role:
      permissionBoundary: arn:aws:iam::534900169478:policy/ScopePermissions
  vpc:
    securityGroupIds:
      - sg-00d713bdedcadb4bc
    subnetIds:
      - subnet-093ac2839ae3deb68

functions:
  execute:
    handler: src/etl.pipe
    role: arn:aws:iam::534900169478:role/utas_lambda_exec_role
    events:
      - s3:
          bucket: utas-etl-bucket-new
          event: s3:ObjectCreated:*
          rules:
            - prefix: incoming/
            - suffix: .csv

package:
  exclude:
    - .venv/**
    - .vscode/**
    - node_modules/**

